name: ADO-self-hosted-pipeline

trigger: none

parameters:

  - name: cherryPickVersions
    displayName: 'Scripts To Undo: Comma Separated List Of Full Version Numbers'
    default: ''
    type: string

  - name: deploymentStages
    type: object
    default: 

    - stage: 'Test'
      databaseName: 'Westwind_Test'
      JDBC: 'jdbc:sqlserver://localhost;database=Westwind_Test;trustServerCertificate=true'
      displayName: 'Undo Test'
      pauseForCodeReview: false
      variableGroupName: 'test_credentials_variable_group'
    
    - stage: 'Prod'
      databaseName: 'Westwind'
      JDBC: 'jdbc:sqlserver://localhost;database=Westwind;trustServerCertificate=true'
      displayName: 'Undo Prod'
      pauseForCodeReview: true
      variableGroupName: 'prod_credentials_variable_group'

variables:
  FLYWAY: 'flyway'
  group: flyway_vars
  cherryPickVersions: ${{parameters.cherryPickVersions}}
stages:

  - ${{each stage in parameters.deploymentStages}}:
    
    - stage: ${{stage.stage}} 
      pool: Default
      displayName: ${{stage.displayName}} 
      jobs:
        - job: Undo
          displayName: Undo
          variables:
          - group: ${{stage.variableGroupName}}
          - group: flyway_vars
          steps:
                
            - script: '$(FLYWAY) undo info -url=${{stage.JDBC}} -user=$(userName) -password=$(password) -cherryPick=$(cherryPickVersions) -licenseKey=$(FLYWAY_LICENSE_KEY)'
              failOnStderr: true
              workingDirectory: #Add working directory location if required
              displayName: 'Execute Undo Scripts'