name: ADO-self-hosted-pipeline

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - migrations/*
    # exclude:
    #   - src/**/md/

parameters:
  - name: deploymentStages
    type: object
    default: 

    # - stage: 'Test'
    #   databaseName: 'Westwind_Test'
    #   JDBC: 'jdbc:sqlserver://localhost;database=Westwind_Test;integratedSecurity=true'
    #   displayName: 'Deploy Test'
    #   pauseForCodeReview: false
    #   variableGroupName: 'test_credentials_variable_group'
    
    - stage: 'Prod'
      databaseName: 'Westwind'
      JDBC: 'jdbc:sqlserver://localhost;database=Westwind;integratedSecurity=true'
      displayName: 'Deploy Prod'
      pauseForCodeReview: true
      variableGroupName: 'prod_credentials_variable_group'

variables:
  FLYWAY: 'flyway'
  SCRIPTS_TO_UNDO: '002,003'
  group: flyway_vars

stages:

  - ${{each stage in parameters.deploymentStages}}:
    
    - stage: ${{stage.stage}} 
      pool: Default
      displayName: ${{stage.displayName}} 
      jobs:
        - job: Undo
          displayName: Undo
          variables:
          - group: ${{stage.variableGroupName}}
          - group: flyway_vars
          steps:
                
            - script: '$(FLYWAY) undo info -url=${{stage.JDBC}} -user=$(userName) -password=$(password) -cherryPick="$(SCRIPTS_TO_UNDO)" -licenseKey=$(FLYWAY_LICENSE_KEY)'
              failOnStderr: true
              workingDirectory: #Add working directory location if required
              displayName: 'Execute Undo Scripts'