name: ADO-self-hosted-pipeline-templatized
 
# trigger:
#   branches:
#     include:
#       - development
#   paths:
#     include:
#       - migrations/*

trigger: none

variables:
- template: templates/vars.yml

stages:
# - template: templates/build.yml
#   parameters:
#     stage: Build
#     displayName: Deploy Build
#     executeBuild: false
#     targetCredentialsVariableGroup: rg_build_credentials_variable_group
#     pipelineParamsVariableGroup: rg_flyway_pipeline_vars

- template: templates/deploy.yml
  parameters:
    stage: Test
    displayName: Deploy Test
    # dependsOn: Build
    pauseForCodeReview: false
    failReleaseIfDriftDetected: false
    generateDriftAndChangeReport: true                   
    staticCodeAnalysis: false                             
    targetCredentialsVariableGroup: rg_test_credentials_variable_group
    pipelineParamsVariableGroup: rg_flyway_pipeline_vars
